name: inka_smart_inventory_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  mobile_scanner: 2.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  get_storage: ^2.0.3
  dio: ^4.0.6
  shimmer: ^2.0.0
  dropdown_search: ^3.0.1
  drop_down_list: ^0.0.4
  find_dropdown: ^1.0.0
  custom_searchable_dropdown: ^2.1.1
  image_picker: ^0.8.3
  provider: ^6.0.4
  editable_image: ^1.1.0
  string_validator: ^0.3.0
  webview_flutter: ^3.0.4
  flutter_launcher_icons: ^0.11.0
  firebase_messaging: ^14.2.0
  firebase_core: ^2.4.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#ffffff"

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
